obj-m:= hello.o

all:

	sudo make -C /lib/modules/5.3.0-42-generic/build M=/home/kaustubh/kernel_modules/hello_1 modules
clean:
	sudo make -C /lib/modules/5.3.0-42-generic/build M=/home/kaustubh/kernel_modules/hello_1 clean
